import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/header";
import StoreProvider from "./StoreProvider";
import TokenRefresher from "@/components/custom/token-refresher";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
      <body
        suppressHydrationWarning
        className={`${manrope.variable} font-[family-name:var(--font-manrope)] antialiased`}
      >
        <TokenRefresher />
        <Header />
        <main>{children}</main>
      </body>
      </StoreProvider>
    </html>
  );
}
